### ISSUE TITLE
Please add a readme.md with guidelines for logo usage by members

### ISSUE THREAD

**Issue by dmueller2001** [cncf/artwork#1]
Could we get a readme.md added to this repo that covers logo use by members?

https://github.com/cncf/artwork/tree/master/cncf

something along the lines of this: 

http://www.linuxfoundation.org/collaborate/workgroups/networking/trademarkusageguidelines

and include this as well:

https://github.com/opencontainers/artwork/blob/master/LICENSE

So member's corporate marketing team's feel a bit more comfortable about using the logo on their sites

**Comment by dankohn** [comment]
Done, thanks.
