### ISSUE TITLE
Kubernetes SVG icons contain broken path

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/artwork#109]
Hi, I was investigating a problem with Kubernetes SVG icon used by DevStats, see: [test server](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) vs [prod server](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1)
![Screenshot 2019-05-16 at 07 28 53](https://user-images.githubusercontent.com/2469783/57828607-52dff500-77ac-11e9-8969-8414325e21b1.png)
![Screenshot 2019-05-16 at 07 29 16](https://user-images.githubusercontent.com/2469783/57828612-55dae580-77ac-11e9-955f-0a6e8ba2f4a3.png)

The test server has an additional white "b" letter visible under the K8s SVG icon. What is more interesting is that it cannot be seen when displaying an icon in a separate page (probably due to white background): [direct link to broken svg](https://all.teststats.cncf.io/public/img/projects/k8s.svg), also displaying that SVG in [GitHub](https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg) does not show this "b" letter.
I've manually fixed that on prod server by editing SVG file in vim (changing first `path` object into `patha` object which is the same as removing first `path` object):
![Screenshot 2019-05-16 at 07 32 17](https://user-images.githubusercontent.com/2469783/57828721-c08c2100-77ac-11e9-8c46-12d968bf5b02.png)
Changed to:
![Screenshot 2019-05-16 at 07 33 25](https://user-images.githubusercontent.com/2469783/57828771-e9141b00-77ac-11e9-8802-de71b5d5c0b8.png)
I was wondering what exactly this path object is, so I've installed `Inkscape` app to see and it's clearly visible that `path` object with `id="bbbbbbb"` is outside of the main viewport.
![Screenshot 2019-05-16 at 07 15 28](https://user-images.githubusercontent.com/2469783/57828822-15c83280-77ad-11e9-9673-943586b834d1.png)
![Screenshot 2019-05-16 at 07 20 53](https://user-images.githubusercontent.com/2469783/57828823-15c83280-77ad-11e9-998b-124f9f9bc00d.png)
There is probably the same problem with black and white SVG icons too, maybe also other files where `its-pronounced` property was added recently.

cc @ZeusTheTrueGod @dankohn

**Comment by lukaszgryglicki** [comment]
Auto-crop program (that generates that SVG) should generate SVG without any paths outside its main viewport. I suggest installing some SVG editor (I've used `Inkscape` on Mac) and checking generated file manually - list all objects and check if all of them are within the viewport, especially this "b" is white and background is also white so this is easy to overlook it without SVG editor.

**Comment by ZeusTheTrueGod** [comment]
Hi, @lukaszgryglicki , thanks for the report.
The way how the svg-autocrop works is that it renders an SVG in chrome browser, analyzes the generated bitmap and adjusts the viewport. Beside that, it uses an svgo package to optimize the svg and make it smaller, but that is not so important here.
I guess the root issue is that this SVG file has an invisible element with 'b' and there is some rendering bug in Chrome when svg is rendered differently and the viewport property is not respected. 

I've played with Chrome a bit, I can say that having min-width: 60px min-height: 60px and attributes width=80px and height=80px is also a bit confusing, with that change,
`
<img class="cncf-proj" src="public/img/projects/k8s.svg" alt="Kubernetes">
` where I'm removing width= and height= attributes, all looks well. I guess that is why the viewport of the SVG was not respected.

**Comment by lukaszgryglicki** [comment]
I'll check tomorrow, but don't you think that it should "just work" when specifying any square width/height combination? I can update all DevStats instances using your suggestion, but I feel like this is a hack to make it work. I think SVGs should "just work" when specifying any size and without additional hidden objects outside their square viewport. All that I specify for Grafana is https://github.com/cncf/devstats/blob/master/partials/projects_health.html#L17-L19, it should not require any more adjustments IMHO, see - all other projects icons are OK.

**Comment by ZeusTheTrueGod** [comment]
I need to check how this new invisible element appeared, it is an interesting bug

**Comment by dankohn** [comment]
Resolved.
