### ISSUE TITLE
OpenTracing color icon SVG is not centered

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/artwork#14]
OpenTracing SVG file is not centered.
See this (GIMP):
![screen shot 2017-11-17 at 13 24 01](https://user-images.githubusercontent.com/2469783/32947148-c0614314-cb9a-11e7-8de5-dea6d5181a56.png)
![screen shot 2017-11-17 at 13 24 06](https://user-images.githubusercontent.com/2469783/32947149-c082806a-cb9a-11e7-8c82-a0b57e21cdbb.png)
![screen shot 2017-11-17 at 13 24 13](https://user-images.githubusercontent.com/2469783/32947150-c09cb584-cb9a-11e7-8a44-4bae77dbd6df.png)

This SVG file:
https://github.com/cncf/artwork/blob/master/opentracing/icon/color/opentracing-icon-color.svg
Originally requested here: https://github.com/cncf/devstats/issues/18

**Comment by lukaszgryglicki** [comment]
Created PR with fix: https://github.com/cncf/artwork/pull/15

**Comment by radoslaw** [comment]
I think a square image should be used such as the one attached
Rad
    On Friday, November 17, 2017, 2:31:41 PM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
Created PR with fix: #15

**Comment by dankohn** [comment]
@radoslaw I don't understand your message. Lukasz's logo is square: https://github.com/lukaszgryglicki/artwork/blob/cee57a435f5f3dec6808cefbbd73e368edc452e9/opentracing/icon/color/opentracing-icon-color.svg

**Comment by radoslaw** [comment]
no, it is 1000x878
Rad
    On Friday, November 17, 2017, 3:34:53 PM GMT+1, Dan Kohn <notifications@github.com> wrote:  
 
 
@radoslaw I don't understand your message. Lukasz's logo is square: https://github.com/lukaszgryglicki/artwork/blob/cee57a435f5f3dec6808cefbbd73e368edc452e9/opentracing/icon/color/opentracing-icon-color.svg

**Comment by dankohn** [comment]
Good point. That may also be why it is not centered in the circle at
https://opentracing.cncftest.io/dashboard/db/dashboards?refresh=15m&orgId=1

Could you please work with Lukasz and one of you can update.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
I can create another PR on Monday. SOrry :( I have no more time today.

**Comment by dankohn** [comment]
Closing for #16.
