### ISSUE TITLE
Embedded "b" letter in the Kubernetes SVG logo

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/artwork#148]
Happens again, it was fixed some time ago.
See:
- https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg
- https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
- https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/black/kubernetes-icon-black.svg

And in DevStats (which syncs artwork periodically):
![Screenshot 2020-01-07 at 13 14 41](https://user-images.githubusercontent.com/2469783/71895008-2bc99f80-3150-11ea-910a-39361ef3f799.png)

**Comment by AndreyKozlov1984** [comment]
@lukaszgryglicki @dankohn ok, done here - https://github.com/cncf/artwork/pull/149
