### ISSUE TITLE
Redo all icons to be square

### ISSUE THREAD

**Issue by dankohn** [cncf/artwork#16]
This will make them more usable in a variety of contexts.

Cc @radoslaw @lukaszgryglicki

**Comment by radoslaw** [comment]
Please note that for instance, 
the opentracing **.ai** icon has the same issue as its **.svg** counterpart
and
the **.png** version is not square, if it matters

I guess other projects' icons may have similar issues. This is in the "color" folder and the "black,white" folders may be affected too.

Also, I suspect someone was fixing the position of those icons. While it may have helped some, it moved others unnecessarily. I suggest changing the -1 for position-top to 0 as seen here:
![screen shot 2017-11-17 at 16 25 25](https://user-images.githubusercontent.com/1783359/32961520-21ebef48-cbc9-11e7-9bba-fe83456b461f.png)

**Comment by dankohn** [comment]
@radoslaw The last issue is unique to how @lukaszgryglicki is using them. I'm expecting @alexcontini to redo the color, black and white versions of all icons in all formats, which should put us on firm ground going forward.

**Comment by lukaszgryglicki** [comment]
Actually, I have no control over how those icons are used.
This is Grafana code.
I only have a "rebranding" script that replaces Grafana icon with our icon.
This cannot be done via any config option, I've even opened a feature request on Grafana repos (some time ago), but They closed it and said they "rebranding is not something we want to support".

**Comment by dankohn** [comment]
Right, but this isn’t an artwork issue. Please open a new issue on devstats to discuss further. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by dankohn** [comment]
@radoslaw Could you please confirm that the icons are square so we can close this issue.

**Comment by radoslaw** [comment]
The icons are now square.

**Comment by dankohn** [comment]
Closing, thanks.
