### ISSUE TITLE
Proper transparency for cloud gopher image

### ISSUE THREAD

**Issue by dankohn** [cncf/artwork#19]
@alexcontini You converted the SVG from Ashley into PNGs. This produces some transparency around the border at https://github.com/cncf/artwork/blob/master/other/illustrations/ashley-mcnamara/cncf-cloud-gophers.png but the center of the picture is white.

However, Ashley's version of the PNG had transparency everywhere for white, causing printing on grey to look like: https://twitter.com/phennex/status/932698316068081666

@ashleymcnamara as the artist, could you please tell us how to best handle transparency. Ashley, also note that the PNG you originally sent looks fine on desktop Twitter at https://twitter.com/dankohn1/status/930057718785888256 but on a phone the transparent background shows as black. I converted the PNG to a JPEG and reposted in a reply to avoid that issue.

Here's the PNG Ashley prepared:

![cncf](https://user-images.githubusercontent.com/3083270/33191026-773c7a5e-d082-11e7-93a9-5d6f6f165c41.png)

And here's a screenshot of my tweet looking bad in Twitter on iOS:

![img_0091](https://user-images.githubusercontent.com/3083270/33191031-8a4ad316-d082-11e7-921e-e87facab92a3.png)

Any suggestions?

**Comment by alexcontini** [comment]
I created a transparent folder with the new files here: https://github.com/cncf/artwork/tree/master/other/illustrations/ashley-mcnamara/transparent
