### ISSUE TITLE
Helm Logo has bad reflection

### ISSUE THREAD

**Issue by AndrewGearhart** [cncf/artwork#195]
The Helm Logo's bottom section is reflected into the top of the wheel when loaded with Adobe Illustrator 24.2.3 (tested on MacOS 10.15.7).

**Comment by AndrewGearhart** [comment]
The curves are also not showing a flat edge above/below the HELM text.

**Comment by alexcontini** [comment]
@AndrewGearhart I think this has been fixed as I am not seeing the issue - https://github.com/cncf/artwork/blob/master/projects/helm/stacked/color/helm-stacked-color.svg - let me know otherwise!

**Comment by AndrewGearhart** [comment]
Yep, looks like [this commit](https://github.com/cncf/artwork/commit/40e2e8948509b40e4bad479446aaec18d6273bf2) fixed it up. Thanks!
