### ISSUE TITLE
QA the new SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/artwork#20]
I found this corrupt SVG: https://github.com/cncf/artwork/blob/master/other/cka/color/kubernetes-cka-color.svg

When saved and loaded in Chrome it gives the error "This page contains the following errors: error on line 81 at column 115: Namespace prefix inkscape for groupmode on g is not defined
Below is a rendering of the page up to the first error."

Please fix and then manually review the rest of the SVGs in GitHub to ensure that the rest of them are correct.

**Comment by alexcontini** [comment]
Hi Dan,

When you have a chance, will you let me know if the attached 2 files are
opening for you properly and no longer giving that error message? I am able
to open, but I was before too and it must have to do with my software that
I used to build it. If these files are good I will re-upload to the correct
folders.

Thank you,

Alex

**Comment by dankohn** [comment]
Attachments don't work via email. You need to use the web editor. But you can test yourself by just dragging the image into an empty tab on Chrome.

**Comment by alexcontini** [comment]
Sounds good, I dragged them both into Chrome and they are not giving me an
error message. I am going to add them to github now.

**Comment by radoslaw** [comment]
I have experienced [some other] images not showing in a web page because of file permissions.
Rad
    On Friday, November 24, 2017, 2:51:31 AM GMT+1, Alex Contini <notifications@github.com> wrote:  
 
 Sounds good, I dragged them both into Chrome and they are not giving me an
error message. I am going to add them to github now.

**Comment by dankohn** [comment]
Rad, please be specific.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by radoslaw** [comment]
To be more specific,
I have seen images uploaded to an Ubuntu 16 server (server has nothing to do with The Linux Foundation) which were not showing to end users in a browser. They were visible locally and had proper content. To the outside world they were not visible because of file permissions. To fix it, a chmod command was issued with value 644.
    On Friday, November 24, 2017, 3:10:56 PM GMT+1, Dan Kohn <notifications@github.com> wrote:  
 
 Rad, please be specific.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
Rad, please delete and reclone the repo and then open a new issue if you
can reproduce the bug.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
@alexcontini Have you QAed all SVGs? Can I close this issue?

**Comment by alexcontini** [comment]
Hi Dan,

Yes I tested all svgs and only found an error when dragging into chrome in
the two that I replaced (kubernetes-cka-color and kubernetes-cka-black).

So you can close, thank you!

Alex
