### ISSUE TITLE
Jaeger png is too small

### ISSUE THREAD

**Issue by dankohn** [cncf/artwork#21]
Compare https://raw.githubusercontent.com/cncf/artwork/master/jaeger/stacked/color/jaeger-stacked-color.png to https://raw.githubusercontent.com/cncf/artwork/master/envoy/stacked/color/envoy-stacked-color.png

**Comment by alexcontini** [comment]
https://raw.githubusercontent.com/cncf/artwork/master/jaeger/stacked/color/jaeger-stacked-color.png - this is now fixed.
