### ISSUE TITLE
Missing Kubernetes 1.20 certified logos

### ISSUE THREAD

**Issue by angelbarrera92** [cncf/artwork#210]
Hi team!

I just wanted to know if you have plans to post/create new logos for the certified Kubernetes 1.20?
I can not find it here: https://github.com/cncf/artwork/tree/master/projects/kubernetes/certified-kubernetes

Thanks!

**Comment by dims** [comment]
Looks like this was fixed.! please close this issue.

**Comment by xmulligan** [comment]
https://github.com/cncf/artwork/tree/master/projects/kubernetes/certified-kubernetes/1.20
