### ISSUE TITLE
Provide CNCF logo with background

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/artwork#211]
Provide CNCF logo with background so that it works nice with backgrounds.

For example, KEDA uses CNCF logo on its README which is fine with standard GitHub theme:
![image](https://user-images.githubusercontent.com/4345663/104731703-64755f00-573c-11eb-83a8-4fdb5ea4c6f2.png)

But those using black theme see this:
![image](https://user-images.githubusercontent.com/4345663/104731678-5aebf700-573c-11eb-8535-625512ea2fc1.png)

**Comment by meenaljain0303** [comment]
Could you assign me this issue. I would like to work on it.

**Comment by alexcontini** [comment]
@tomkerkhove  sorry for the delay here! I have added the logos with color icon and white text - https://github.com/cncf/artwork/tree/master/other/cncf/horizontal/color-whitetext - let me know if that doesn't work
