### ISSUE TITLE
Add Flagger logos

### ISSUE THREAD

**Issue by dholbach** [cncf/artwork#229]
Flagger (a Flux project) logos are currently only available at https://github.com/fluxcd/flagger/tree/main/docs/logo

It'd be good if they were in https://github.com/cncf/artwork/tree/master/projects as well, so the `Flagger` entry in https://github.com/cncf/landscape/blob/master/landscape.yml and https://github.com/cncf/cncf-branding could refer to them too.

CC @bia and @stefanprodan

**Comment by xmulligan** [comment]
@alexcontini can you help here?

**Comment by alexcontini** [comment]
@xmulligan Flagger logos have been added: https://github.com/cncf/artwork/blob/master/examples/sandbox.md#flagger-logos

**Comment by dholbach** [comment]
I filed https://github.com/cncf/artwork/pull/249 - after that I believe this issue can be closed?
