### ISSUE TITLE
helm can not install or update if k8s service exist ,but k8s service must remain as it is prod environment.

### ISSUE THREAD

**Issue by shifeichen** [cncf/artwork#232]
we want convert exist k8s service format to helm, but remain k8s service

we excute the command:

helm install topevents --set AppName=topevents,Environment=prod,ServiceArea=analyticsservices  ./

Error: rendered manifests contain a resource that already exists. Unable to continue with install: Deployment "topevents" in namespace "analyticsservices-prod" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "topevents": current value is "topenvents"

yes, i know why.

but just want to know how to solve this issue.

**Comment by xmulligan** [comment]
Hi @shifeichen please ask this question in the helm slack https://kubernetes.slack.com/archives/C0NH30761 or helm repo https://github.com/helm/helm
