### ISSUE TITLE
Pravega logo without the text

### ISSUE THREAD

**Issue by fpj** [cncf/artwork#243]
Would it be possible to have images of the Pravega bird without the text `Pravega - Realiable...`?

https://github.com/cncf/artwork/tree/master/projects/pravega/

**Comment by caniszczyk** [comment]
when ever you have time @alexcontini, not super high priority atm :)

**Comment by alexcontini** [comment]
@caniszczyk @fpj updated! https://github.com/cncf/artwork/tree/master/projects/pravega/horizontal-notext

**Comment by fpj** [comment]
Thank you, @caniszczyk and @alexcontini.
