### ISSUE TITLE
Help on adding sandbox project (vineyard) logo to artwork

### ISSUE THREAD

**Issue by sighingnow** [cncf/artwork#255]
Hi @amye and @poconnor1,

(I'm not sure here is the right place to get help about artwork from CNCF service).

We are the team behind the sandbox project vineyard and we are in [the onboarding process](https://github.com/cncf/toc/issues/645). It seems that [CNCF could help on artwork artifacts](https://github.com/cncf/landscape#logos) and we would like to know could CNCF help us to convert our logo (in `.ai` format) to required variant versions (horizontal, stacked, icon, and png/svg formats)?

I have uploaded [our logo's AI file](https://github.com/cncf/artwork/files/6569128/vineyard.ai.zip) in this issue.

Thanks!

**Comment by caniszczyk** [comment]
LGTM!

**Comment by sighingnow** [comment]
@alexcontini It is so nice of you to help us on the artwork!

> I didn't include a horizontal version as there wasn't one in the AI file, let me know if there are any problems!

I have attached the horizontal version in png format. It is derived from the AI file above but we (the team member) don't know how to process it to svg and black/white version.

Could you help us to make the horizontal version from the png file? Thanks in advance!

![vineyard-logo-h](https://user-images.githubusercontent.com/7144772/121551890-974d2600-ca42-11eb-8081-122df29c41a6.png)

**Comment by alexcontini** [comment]
@sighingnow  sounds good! I have added the horizontal logos to the artwork repo - https://github.com/cncf/artwork/blob/master/examples/sandbox.md#vineyard-logos

**Comment by sighingnow** [comment]
> @sighingnow sounds good! I have added the horizontal logos to the artwork repo - https://github.com/cncf/artwork/blob/master/examples/sandbox.md#vineyard-logos

That looks pretty good. Thanks a lot @alexcontini
