### ISSUE TITLE
Missing Kubernetes 1.21 certified logos

### ISSUE THREAD

**Issue by artberger** [cncf/artwork#257]
Hello, our product recently passed conformance testing for Kubernetes 1.21, and we usually grab the logo from the following repo. However, I didn’t see 1.21 in there. I was wondering if anyone had this?

https://github.com/cncf/artwork/tree/master/projects/kubernetes/certified-kubernetes

Related Slack request here: https://kubernetes.slack.com/archives/C78F00H99/p1623248294017200

**Comment by xmulligan** [comment]
@alexcontini do you know where it is?

**Comment by alexcontini** [comment]
@xmulligan  @artberger  I added the 1.21 files here: https://github.com/cncf/artwork/tree/master/projects/kubernetes/certified-kubernetes/1.21

**Comment by artberger** [comment]
Thank you so much, so fast!
