### ISSUE TITLE
Conscious Logo / Diverse logos?

### ISSUE THREAD

**Issue by fabiand** [cncf/artwork#268]
Hey,

to support diversity in our community I was wondering if the artwork team can help to create diverse logos of the cncf projects. Can it?

**Comment by amye** [comment]
@fabiand  - not sure what you're looking for here

**Comment by fabiand** [comment]
At some point I saw i.e. K8s logos in rainbow colors. I was thinking of something like this.

**Comment by amye** [comment]
Right, we do those for Pride! 
If you want something specific, use servicedesk.cncf.io 🥰

**Comment by fabiand** [comment]
Right, and do you provide them for every CNCF project? I did not see such a variant in https://github.com/cncf/artwork/tree/master/projects/kubevirt/icon

**Comment by amye** [comment]
We only do the K8s one currently, but if you want something specific, servicedesk ticket.

**Comment by fabiand** [comment]
Ack thanks!
