### ISSUE TITLE
Jaeger color versions have no white in their eyes - cursed imagery

### ISSUE THREAD

**Issue by mic-max** [cncf/artwork#307]
![image](https://user-images.githubusercontent.com/15165028/140570327-02af0b4f-6274-4b6e-9e13-60780b37bd63.png)

I don't believe this is intended. The eyes will be the colour of the background. I think same goes for the eyebrows.

https://github.com/cncf/artwork/blob/master/projects/jaeger/stacked/color/jaeger-stacked-color.png

**Comment by alexcontini** [comment]
@mic-max  I have updated the color logos to include eye whites! https://github.com/cncf/artwork/tree/master/projects/jaeger - let me know if that doesn't work
