### ISSUE TITLE
Add KCNA to other examples

### ISSUE THREAD

**Issue by Rabattkarte** [cncf/artwork#329]
https://github.com/cncf/artwork/blob/master/examples/other.md

Currently, KCNA is missing as an example for certifications.

**Comment by Rabattkarte** [comment]
I just realized that this is a global concern and not just for the examples. :)

**Comment by thetwopct** [comment]
Just doing some housekeeping of issues - KCSA and other certifications are now added under examples/other

https://github.com/cncf/artwork/blob/main/examples/other.md#kubernetes-certification-logos
