### ISSUE TITLE
Cloud Native Community Groups logo missing 

### ISSUE THREAD

**Issue by JacobValdemar** [cncf/artwork#337]
https://community.cncf.io

The logo for Cloud Native Community Groups seems to be missing

**Comment by techmaharaj** [comment]
Hi @caniszczyk can you tell me where I can find this logo? It isn't there in the artwork folder. 

We're planning a local chapter meetup and wanted to use this logo for the banners that we plan to create. 

This is the image:
![image](https://user-images.githubusercontent.com/10296271/224240145-d5f23a10-790a-485e-bae7-9026d26e128e.png)


Source: https://res.cloudinary.com/startup-grind/image/upload/dpr_2.0,fl_sanitize/v1/gcs/platform-data-cncf/contentbuilder/logo_light_backgrounds_cGIXYU4.svg
