### ISSUE TITLE
Update Certified CNF Brand Guide pdf

### ISSUE THREAD

**Issue by lixuna** [cncf/artwork#342]
A new version of the Certified CNF Brand Guide is available to be uploaded to this url: https://github.com/cncf/artwork/blob/master/other/certified-cnf/certified-cnf-brand-guide.pdf

Please remove the placeholder image (comic sans text) and upload the attached pdf.

Thank you for your help! 

[CNF_Certified_BrandGuide_061322.pdf](https://github.com/cncf/artwork/files/8920172/CNF_Certified_BrandGuide_061322.pdf)

**Comment by lixuna** [comment]
cc @KTan1226 @Charley-Mann @cjyabraham

**Comment by thetwopct** [comment]
(Housekeeping) Looks like this was done, thanks!
