### ISSUE TITLE
Add KubeCon + CloudNativeCon speaker badge

### ISSUE THREAD

**Issue by Dentrax** [cncf/artwork#358]
It would be nice to have an official KubeCon + CloudNativeCon speaker badge in this repo. This is how Credly did:

![Screen Shot 2022-09-17 at 22 36 25](https://user-images.githubusercontent.com/16493751/190873765-f2a6c861-370b-4dc4-88d3-af46a4f3291e.png)

**Comment by caniszczyk** [comment]
We will get these done with credly right around kubecon :)
