### ISSUE TITLE
Missing certified Kubernetes badges for 1.24 and 1.25

### ISSUE THREAD

**Issue by ralgozino** [cncf/artwork#368]
Hello 👋 

The certified Kubernetes badges for 1.24 and 1.25 are missing [here](https://github.com/cncf/artwork/tree/master/projects/kubernetes/certified-kubernetes).

Do you plan to maintain them or should we use the version-less version from now on?

Thank you!

**Comment by amye** [comment]
@taylorwaggoner - you may know more about this?

**Comment by taylorwaggoner** [comment]
@amye @ralgozino  thanks!  I'll get 1.24 and 1.25 added soon!

**Comment by mitalipaygude** [comment]
Thank you @taylorwaggoner

**Comment by TerryHowe** [comment]
Any progress here? I'd submit a PR, but my image skills are lacking.

**Comment by ralgozino** [comment]
this has been fixed in #385 

thanks @alexcontini @caniszczyk
