### ISSUE TITLE
Q: Can maintainers create a derivative of the artwork?

### ISSUE THREAD

**Issue by AkihiroSuda** [cncf/artwork#375]
As a maintainer of [containerd](https://github.com/containerd) (CNCF Graduated), including its subproject [nerdctl](https://github.com/containerd/nerdctl) (contaiNERD CTL), I'd like to alter the containerd logo for creating the nerdctl logo:

### containerd logo
<img src="https://raw.githubusercontent.com/cncf/artwork/master/projects/containerd/horizontal/color/containerd-horizontal-color.png" width=200 />

### Proposed nerdctl logo
:warning: Spaces and the font of the "l" character is subject to change

<img src="https://user-images.githubusercontent.com/16693043/203749424-768b089f-f98f-4b4f-a503-c67a05885f16.svg" width=200 />

Do I need to get approval from LF/CNCF, in addition to other containerd maintainers?

**Comment by developer-guy** [comment]
Not a maintainer, but it looks good to me 🥳 I've requested to create a nerdctl logo because we are going to add it to the landscape created by the [OpenSSF community](https://landscape.openssf.org) as an integrator of the [Sigstore](https://landscape.openssf.org/sigstore).

/cc @tracymiranda

**Comment by developer-guy** [comment]
kindly ping @caniszczyk @alexcontini  ☝️

**Comment by nate-double-u** [comment]
Hi, according to the [LICENSE file](https://github.com/cncf/artwork/blob/main/LICENSE.md), all artwork in this repo is made available under the Linux Foundation trademark usage [guidelines](https://www.linuxfoundation.org/trademark-usage/):

> If you have questions with respect to these guidelines..., or to obtain written permission for a proposed use of The Linux Foundation trademarks, contact: [trademarks@linuxfoundation.org](mailto:trademarks@linuxfoundation.org)

I think that this question is likely best asked of the LF trademarks folks directly.

**Comment by AkihiroSuda** [comment]
Asked the LF, and they allowed it
