### ISSUE TITLE
Missing Prometheus Logo text

### ISSUE THREAD

**Issue by edsiper** [cncf/artwork#4]
Prometheus Logo don't have the _text_. Kubernetes have the logo plus the text in .svg format.

**Comment by caniszczyk** [comment]
cc: @juliusv

**Comment by SuperQ** [comment]
Logo text is Lato Light, http://www.latofonts.com/lato-free-fonts/

**Comment by dankohn** [comment]
This has now been fixed in both the horizontal and stacked version: https://github.com/cncf/artwork/tree/master/prometheus

Please speak up if we didn't get anything exactly right. (Though note we're addressing extra space in SVGs in #17)
