### ISSUE TITLE
Logos/Artwork 

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/artwork#463]
OpenKruise logo in the landscape needs to be updated to **[this](https://github.com/cncf/artwork/blob/main/projects/openkruise/stacked/color/openkruise-stacked-color.png)**.
Keycloak is an incubating project and isn’t found in the CNCF artwork repo, **[here](https://github.com/keycloak/keycloak-misc/tree/main/logo)** is a link to their GitHub logos file. 
Keycloak logo in CNCF landscape should be the stacked [**logo**](https://github.com/keycloak/keycloak-misc/blob/main/logo/logo-stacked.svg).
Karmada is now incubating and is still under “Sandbox” in the CNCF logos repo.

**Comment by taylorwaggoner** [comment]
@Cmierly @amye who updates/adds project logos these days?

**Comment by amye** [comment]
We can reach out to the projects to update.

**Comment by thetwopct** [comment]
All issues from the original issue seem to be fixed now 👍
