### ISSUE TITLE
New Cloudevents logo

### ISSUE THREAD

**Issue by dankohn** [cncf/artwork#67]
Please take the new artwork at https://github.com/cloudevents/spec/tree/master/artwork and convert it into our standard formats here and replace what we have. Once the PR has been merged, please open a PR on https://github.com/cloudevents/spec/tree/master/artwork to delete that directory and instead reference this repo. Then ask Taylor to order new stickers at https://store.cncf.io/collections/cloudevent

Cc @taylorwaggoner @ac360 @duglin

**Comment by duglin** [comment]
ping @barkerd427 since this might impact our web site

**Comment by barkerd427** [comment]
Following, thanks!

**Comment by dankohn** [comment]
Can I please get a signoff from some of @ac360 @duglin @barkerd427  on https://github.com/cncf/artwork/pull/68 and then I'll merge.

**Comment by duglin** [comment]
Can this be closed now or is there more work to be done?

**Comment by duglin** [comment]
@taylorwaggoner are the new stickers ordered?

**Comment by dankohn** [comment]
Yes, they've been ordered and will be there in a week or so. Please close.

**Comment by duglin** [comment]
I don't have permission to close it
