### ISSUE TITLE
The "cropped" CNCF logo doesn't exist in CNCF directory

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/artwork#8]
As a CNCF Ambassador, I would like to use "cropped" CNCF logo for various promotion activities.

Unfortunately, it is not provided under CNCF directory.

"Cropped" logo [sample](https://avatars3.githubusercontent.com/u/13455738?v=3&s=200).

**Comment by dankohn** [comment]
Added here: https://github.com/cncf/artwork/tree/master/cncf/icon/color

**Comment by mgoodness** [comment]
Thanks, @dankohn. This will come in very handy!

**Comment by radoslaw** [comment]
Good,
Please note that for instance, the opentracing .ai icon has the same issue as its .svg counterpartand
the .png version is not square, if it matters
I guess other projects' icons may have similar issues
Also, I guess someone was fixing the position of those icons. While it may have helped some, it moved others unnecessarily. I suggest changing the -1 for position-top to 0 as seen here:



Rad
    On Friday, November 17, 2017, 4:17:27 PM GMT+1, Michael Goodness <notifications@github.com> wrote:  
 
 
Thanks, @dankohn. This will come in very handy!

**Comment by dankohn** [comment]
@radoslaw Please add your comments to GitHub for better formatting rather than sending by email. Also email attachments do not come across to GitHub.

Finally, the square icon issue is #16
