### ISSUE TITLE
Prometheus 'grey' transparent PNG logo is not grey

### ISSUE THREAD

**Issue by mattbostock** [cncf/artwork#9]
[`prometheus/prometheus_grey_transparent.png`](https://github.com/cncf/artwork/blob/25dd3218bb1aba51fff07add00dbd7360adec2ae/prometheus/prometheus_grey_transparent.png) is orange rather than grey.

/cc @juliusv

**Comment by juliusv** [comment]
@mattbostock Indeed, I can reproduce :) Thanks! Fix in https://github.com/cncf/artwork/pull/10

**Comment by dankohn** [comment]
This has now been addressed, thanks.

https://github.com/cncf/artwork/blob/master/prometheus/horizontal/color/prometheus-horizontal-color.png
https://github.com/cncf/artwork/blob/master/prometheus/stacked/color/prometheus-stacked-color.png
