### ISSUE TITLE
Clarification of logo usage

### ISSUE THREAD

**Issue by sitereactor** [cncf/artwork#97]
Hi,

I have been looking at the License and at the linked trademark usage page here: https://www.linuxfoundation.org/trademark-usage/ in order to figure out if its allowed to get the logos printed as stickers/magnets to give out at events. I know you point to certain logos being available in a CNCF online store, but when that is not sufficient are you allowed to get them printed yourself?

For clarity, this is for giving away at local cloud native community events for free.
I just want to make sure its not a copyright infringement.

Thanks!

**Comment by dankohn** [comment]
Thanks for checking. Yes, you're welcome to print your own stickers. The issue would be that you shouldn't also print your company logo on the sticker (implying that one belongs to the other). You're also welcome to order from https://store.cncf.io/.

**Comment by sitereactor** [comment]
Great, thanks for the quick reply. I wouldn't want to change the logos in any way. So sounds like it should be fine. I will check the cncf store as well. Thanks!
